version: '2.2'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rezdyImage
    ports:
      - 8080
    networks:
      - network1
    scale: 1

networks:
  network1:
